version: '3.8'
services:
  backend:
    build:
      context: ../  
      dockerfile: docker/Dockerfile  
    ports:
      - "8080:80"  
    depends_on:
      - postgres
      - clickhouse
    environment:  
      - ConnectionStrings__Postgres=Host=postgres;Port=5432;Database=steamdb;Username=postgres;Password=123456
      - ClickHouseConnection=Host=clickhouse;Port=8123;Username=default;Password=;Database=default
      - ASPNETCORE_ENVIRONMENT=Development  
      - ASPNETCORE_URLS=http://+:80  

  postgres:
    image: postgres:16 
    environment:  # Env для Postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=steamdb
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"  # Доступ к БД снаружи (для теста в pgAdmin)
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Данные сохраняются

  clickhouse:
    image: clickhouse/clickhouse-server:24 
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse-data:/var/lib/clickhouse 

volumes:
  postgres-data:
  clickhouse-data: